### PR TITLE
Update minimal C# demo

### PR DESCRIPTION
**Pull request by bernardnormier**
A small update to the minimal demo to make it more correct / cleaner.

### CODE REVIEW

**Comment by bernardnormier** [comment]
See also #181.

**Comment by externl** [comment]
Do we care about de-sycnronizing this one demo from the rest? Should we update all of the minimal demos?

**Review by pepone — APPROVED** [review]
Should we update other language mappings?

**Review by externl — APPROVED** [review]

**Comment by bernardnormier** [comment]
Yes, I am in favor of updating all the other minimal demos.

**Pull request merged**
